name: Filter-Macro
version: 0.01
abstract: Make macro modules that are expanded inline
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  Filter::Simple: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
